apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "aws-example-octodex-ingress"
  namespace: "default"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: aws-example-octodex-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "aws-example-octodex"
              servicePort: 80
